apiVersion: v1
kind: Service
metadata:
  name: sample-service-stable
  labels:
    name: springboot-k8s-mysql
spec:
  ports:
    - nodePort: 30163
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: springboot-k8s-mysql
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: session-service-canary
  labels:
    name: springboot-k8s-mysql
spec:
  ports:
    - nodePort: 30164
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: springboot-k8s-mysql
  type: NodePort
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: sample-serivce-mysql-canary-rollout
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: springboot-k8s-mysql
  template:
    metadata:
      labels:
        app: springboot-k8s-mysql
    spec:
      containers:
        - name: springboot-k8s-mysql
          image: atulgupta2593/sample-service-mysql:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
  strategy:
    canary:
      stableService: sample-service-stable
      canaryService: sample-service-canary
      steps:
      - setWeight: 10
      - pause: {duration: 10}
      - setWeight: 20
      - pause: {duration: 10}
      - setWeight: 50
      - pause: {}            
---
